name: finance_tracker
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  cloud_firestore: ^3.1.17
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter_screenutil: ^5.5.3+2
  provider: ^6.0.3
  google_fonts: ^3.0.1
  expandable_page_view: ^1.0.14
  syncfusion_flutter_datepicker: ^20.1.59
  intl: ^0.17.0
  uuid: ^3.0.6
  sliding_up_panel: ^2.0.0+1
  percent_indicator: ^4.2.2
  fl_chart: ^0.55.0
  flutter_launcher_icons: ^0.9.3
  adaptive_theme: ^3.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.3+1

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  android: true
  ios: true
  color_dark: "#121212"
  image_dark: assets/images/splash.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher.png"
  
  



flutter:

  uses-material-design: true

  assets:
    - assets/images/


  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
